theme: minima
title: OpenDAPI
description: An open protocol for creating self-discoverable and self-governed datasets.
header_pages:
  - usage/index.md
  - usage/advanced.md
  - background/index.md
  - usage/fundamentals.md
  - spec/index.md
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/WovenCollab/OpenDAPI" }
